version: '2'

services:
  nginx:
    image: bitnami/nginx:1.10.2-r1
    volumes:
      - ./config/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - backend
      - frontend
    environment:
      - VIRTUAL_HOST=yourproject.docker
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080
  db:
    image: postgres:9.6.1-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=app_development
  backend:
    build: .
    command: rails s --binding=0.0.0.0
    entrypoint: ./scripts/backend_entrypoint.sh
    links:
      - db
      - frontend
    volumes:
      - ./:/app
    depends_on:
      - db
      - frontend
  frontend:
    build: ./client
    command: npm start
    entrypoint: ./scripts/frontend_entrypoint.sh
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: development
